### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by passsy** [passsy/gh-tidy-clone#1]
ARM support for macos would be great

**Comment by passsy** [comment]
Blocked by https://github.com/cli/gh-extension-precompile/pull/3

**Comment by mislav** [comment]
The [latest GitHub CLI 2.8.0 release](https://github.com/cli/cli/releases/tag/v2.8.0) fixes this by falling back to `amd64` binary if Rosetta is installed. If an `arm64` binary is found, for example as a product of the [latest gh-extension-precompile action](https://github.com/cli/gh-extension-precompile/releases/tag/v1.1.2), however, then its codesigning is fixed after downloading to allow execution by the OS.

**Comment by passsy** [comment]
Works ❤️
